Repository ZeRiix/Billy, pull requests merged in 2023-12, with the labels that each got.

#27 Adding feature role + fix feature organization
  .vscode/settings.json
  app/config/services.yaml
  app/src/Controller/OrganizationController.php
  app/src/Controller/RoleController.php
  app/src/Entity/Organization.php
  app/src/Entity/User.php
  app/src/Form/CreateRoleForm.php
  app/src/Form/GiveRoleData.php
  app/src/Form/GiveRoleForm.php
  app/src/Repository/RoleRepository.php
  app/src/Services/Organization/OrganizationService.php
  app/src/Services/Role/RoleService.php
  app/templates/role/give_role.html.twig
  app/templates/role/index.html.twig
Labels: enhancement

#28 [FIX]: fix error condition permission
  app/src/Controller/RoleController.php
Labels: bug

#29 [ADD]: list and delete role
  app/src/Controller/RoleController.php
  app/src/Form/DeleteRoleForm.php
  app/src/Services/Role/RoleService.php
  app/templates/role/delete_role.html.twig
  app/templates/role/list_role.html.twig
Labels: enhancement

#26 Feat/dashboard
  .vscode/settings.json
  app/public/assets/js/accordion.js
  app/src/Controller/DashboardController.php
  app/templates/components/header.html.twig
  app/templates/components/sidebar.html.twig
  app/templates/dashboard/index.html.twig
  app/templates/dashboard/myOrganization.html.twig
  app/templates/dashboard/organizations.html.twig
  app/templates/home/index.html.twig
Labels: enhancement

#30 Feature/client
  app/config/services.yaml
  app/src/Controller/ClientController.php
  app/src/Controller/OrganizationController.php
  app/src/Controller/RoleController.php
  app/src/Entity/Client.php
  app/src/Entity/InviteOrganization.php
  app/src/Entity/Organization.php
  app/src/Entity/Role.php
  app/src/Entity/User.php
  app/src/Form/CreateRoleForm.php
  app/src/Form/DeleteOrganizationForm.php
  app/src/Form/InviteUserForm.php
  app/src/Form/LeaveOrganizationByForm.php
  app/src/Form/LeaveOrganizationForm.php
  app/src/Middleware/GetOrganizationMiddleware.php
  app/src/Middleware/PermissionMiddleware.php
  app/src/Repository/ClientRepository.php
  app/src/Repository/InviteOrganizationRepository.php
  app/src/Repository/OrganizationRepository.php
  app/src/Repository/RoleRepository.php
  app/src/Services/Client/ClientService.php
  app/src/Services/Organization/OrganizationService.php
  app/src/Services/Role/RoleService.php
  app/templates/organization/delete_organization.html.twig
  app/templates/organization/invite_user.html.twig
  app/templates/organization/leave_user.html.twig
  app/templates/organization/leave_user_by.html.twig
Labels: bug, enhancement

#33 Feature/client
  app/src/Controller/ClientController.php
  app/src/Controller/OrganizationController.php
  app/src/Controller/RoleController.php
  app/src/Form/CreateClientForm.php
  app/src/Form/DeleteRoleForm.php
  app/src/Form/UpdateClientForm.php
  app/src/Form/UpdateRoleForm.php
  app/src/Middleware/Client/UserCanUpdateClientMiddleware.php
  app/src/Middleware/Organization/UserCanLeaveOrganizationMiddleware.php
  app/src/Middleware/PermissionMiddleware.php
  app/src/Middleware/Role/UserCanUpdateRoleMiddleware.php
  app/src/Services/Client/ClientService.php
  app/src/Services/Organization/OrganizationService.php
  app/src/Services/Role/RoleService.php
  app/src/Services/Token/TokenService.php
  app/templates/client/client.html.twig
  app/templates/client/clients.html.twig
  app/templates/client/create_client.html.twig
  app/templates/client/index.html.twig
  app/templates/client/update_client.html.twig
  app/templates/organization/invite_user.html.twig
  app/templates/role/delete_role.html.twig
  app/templates/role/index.html.twig
  app/templates/role/update_role.html.twig
Labels: enhancement

#34 [FIX]: fix name update client controller
  app/src/Controller/ClientController.php
Labels: bug

#35 -[FIX]: adding redirect middleware
  app/src/Controller/OrganizationController.php
  app/src/Middleware/Organization/RedirectOwnerOnListOrganizationMiddleware.php
Labels: bug
